[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-openstack"
  version = "v1.15.1"

  [constraint.metadata]
    govendor-exclude-prefixes = ["github.com/golang/protobuf"]
    govendor-override = true

# NOTE: the following overrides were injected by govendor-override. It may be necessary to
# remove some of these overrides in order to produce a buildable vendor tree.
[[override]]
  name = "github.com/Unknwon/com"
  revision = "28b053d5a2923b87ce8c5a08f3af779894a72758"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/agext/levenshtein"
  revision = "5f10fee965225ac1eecdc234c09daf5cd9e7f7b6"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "7e4b007599d4e2076d9a81be723b3912852dda2c"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-rundeck-api"
  revision = "f6af74d34d1ef69a511c59173876fc1174c11f0d"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-textseg"
  revision = "b836f5c4d331d1945a2fead7188db25432d73b69"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/armon/go-radix"
  revision = "1fca145dffbcaa8fe914309b1ec0cfc67500fe61"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.8.34"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/bgentry/speakeasy"
  revision = "4aabc24848ce5fd31929f7d1e4ea74d3709c14cd"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/blang/semver"
  revision = "2ee87856327ba09384cabd113bc6b5d174e9ec0f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/davecgh/go-spew"
  revision = "346938d642f2ec3594ed81d874461961cd0faa76"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/fatih/color"
  revision = "507f6050b8568533fb3f5504de8e5205fa62a114"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/fsouza/go-dockerclient"
  revision = "1d4f4ae73768d3ca16a6fb964694f58dc5eba601"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/go-ini/ini"
  revision = "766e555c68dc8bda90d197ee8946c37519c19409"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "bb1ef8ce758cba00104a697a03ab07c77940f87e"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/gophercloud/utils"
  revision = "fbb6ab446f0167dfa4d25b8eb0c0d2f873924516"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "3573b8b52aa7b37b9358d966a898feb387f62437"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-getter"
  revision = "3f60ec5cfbb2a39731571b9ddae54b303bb0a969"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-hclog"
  revision = "69ff559dc25f3b435631604f573a5fa1efdb6433"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f09973e19c1dfcd120b2d9c4f168e68d6b5d5"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "e8d22c780116115ae5624720c9af0c97afe4f551"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-safetemp"
  revision = "b1a1dbde6fdc11e3ae79efd9039009e22d4ae240"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-uuid"
  revision = "36289988d83ca270bc07c234c36f364b0dd9c9a7"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-version"
  revision = "e96d3840402619007766590ecea8dd7af1292276"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl"
  revision = "a4b07c25de5ff55ad3b8936cea69a79a3d95a855"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl2"
  revision = "9db880accff19d9bd953958df738ef0c02b4a311"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hil"
  revision = "fac2259da677551de1fb92b844c4d020a38d8468"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/logutils"
  revision = "0dc08b1671f34c4250ce212759ebd880f743d883"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/terraform"
  revision = "313108201dd0b2f639776890ada0ac08e0a88b84"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/yamux"
  revision = "d1caa6c97c9fc1cc9e83bbe34d0603f9ff0ce8bd"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mattn/go-colorable"
  revision = "efa589957cd060542a26d2dd7832fd6a6c6c3ade"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mattn/go-isatty"
  revision = "6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/cli"
  revision = "c48282d14eba4b0817ddef3f832ff8d13851aefd"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/copystructure"
  revision = "d23ffcb85de31694d6ccaa23ccb4a03e55c1303f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-testing-interface"
  revision = "a61a99592b77c9ba629d254a693acffaeb4b7e28"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/hashstructure"
  revision = "6b17d669fac5e2f71c16658d781ec3fdd3802b69"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "53818660ed4955e899c0bcafa97299a388bd7c8e"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "63d60e9d0dbc60cf9164e6510889b0db6683d98c"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/oklog/run"
  revision = "6934b124db28979da51d3470dadfa34d73d72652"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/pmezard/go-difflib"
  revision = "792786c7400a136282c1664665ae0a8db921c6c2"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/posener/complete"
  revision = "e037c22b2fcfa85e74495388f03892ed194bba76"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/rancher/go-rancher"
  revision = "ec24b7f12fca9f78fbfcd62a0ea8bce14ade8792"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "b061729afc07e77a8aa4fad0a2fd840958f1942a"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/stretchr/testify"
  revision = "8019298d9fa5a04fc2ad10ae03349df3483096a6"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/ulikunitz/xz"
  revision = "0c6b41e72360850ca4f98dc341fd999726ea007f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/zclconf/go-cty"
  revision = "d006e4534bc4fbc512383aa98d04d641ea951ba5"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/crypto"
  revision = "b176d7def5d71bdd214203491f89843ed217f420"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/net"
  revision = "5f9ae10d9af5b1c89ae6904293b14b064d4ada23"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/sys"
  revision = "bb9c189858d91f42db229b04d45a4c3d23a7662a"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/text"
  revision = "7922cc490dd5a7dbaa7fd5d6196b49db59ac042f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "google.golang.org/grpc"
  revision = "7263089022e5a1615620b463eb70f4757697a873"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "gopkg.in/yaml.v2"
  revision = "eb3733d160e74a9c7e442f435eb3bea458e1d19f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.6.1"
  [override.metadata]
    govendor-overridden=true
