env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  OS_AUTH_URL: https://auth.cloud.ovh.net/v3/
  OS_IDENTITY_API_VERSION: 3
  OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
  OS_PROJECT_DOMAIN_NAME: Default
  OS_REGION_NAME: UK1
  OS_TENANT_ID: 9d596a0506974e0f8c79673edf0bbdd3
  OS_TENANT_NAME: "9616699805113213"
  OS_USER_DOMAIN_NAME: Default
  OS_USERNAME: jrGMbHHjkUQ7
  PROVIDER: openstack
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_API: https://api.pulumi-staging.io
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  TRAVIS_OS_NAME: linux
jobs:
  comment-on-pr:
    if: github.event.pull_request.head.repo.full_name != github.repository
    name: comment-on-pr
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@1.0.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          PR is now waiting for a maintainer to run the acceptance tests.
          **Note for the maintainer:** To run the acceptance tests, please comment */run-acceptance-tests* on the PR
    strategy: {}
name: pull-request
"on":
  pull_request_target: {}
